import type { Achievement } from '../types';

export const ACHIEVEMENTS: Omit<
  Achievement,
  'unlocked' | 'unlockedAt' | 'progress'
>[] = [
  // Productivity
  {
    id: 'first-task',
    name: 'First Steps',
    description: 'Complete your first task',
    category: 'productivity',
    icon: '🎯',
    threshold: 1,
    metric: 'totalTasks',
  },
  {
    id: 'ten-tasks',
    name: 'Getting Things Done',
    description: 'Complete 10 tasks',
    category: 'productivity',
    icon: '✅',
    threshold: 10,
    metric: 'totalTasks',
  },
  {
    id: 'fifty-tasks',
    name: 'Task Master',
    description: 'Complete 50 tasks',
    category: 'productivity',
    icon: '🏆',
    threshold: 50,
    metric: 'totalTasks',
  },
  {
    id: 'hundred-tasks',
    name: 'Centurion',
    description: 'Complete 100 tasks',
    category: 'productivity',
    icon: '💯',
    threshold: 100,
    metric: 'totalTasks',
  },
  // XP
  {
    id: '100xp',
    name: 'Century XP',
    description: 'Earn 100 XP',
    category: 'productivity',
    icon: '⚡',
    threshold: 100,
    metric: 'totalXP',
  },
  {
    id: '500xp',
    name: 'Power Player',
    description: 'Earn 500 XP',
    category: 'productivity',
    icon: '⚡',
    threshold: 500,
    metric: 'totalXP',
  },
  {
    id: '1000xp',
    name: 'XP Hunter',
    description: 'Earn 1000 XP',
    category: 'productivity',
    icon: '⚡',
    threshold: 1000,
    metric: 'totalXP',
  },
  // Streak
  {
    id: '3-streak',
    name: 'On Fire',
    description: 'Maintain a 3-day streak',
    category: 'streak',
    icon: '🔥',
    threshold: 3,
    metric: 'currentStreak',
  },
  {
    id: '7-streak',
    name: 'Week Warrior',
    description: 'Maintain a 7-day streak',
    category: 'streak',
    icon: '🔥',
    threshold: 7,
    metric: 'currentStreak',
  },
  {
    id: '30-streak',
    name: 'Unstoppable',
    description: 'Maintain a 30-day streak',
    category: 'streak',
    icon: '🔥',
    threshold: 30,
    metric: 'currentStreak',
  },
  {
    id: 'longest-7',
    name: 'Consistency King',
    description: 'Reach a 7-day longest streak',
    category: 'streak',
    icon: '👑',
    threshold: 7,
    metric: 'longestStreak',
  },
  // Eco
  {
    id: '10-trees',
    name: 'Tree Hugger',
    description: 'Save 10 trees',
    category: 'eco',
    icon: '🌳',
    threshold: 10,
    metric: 'treesSaved',
  },
  {
    id: '100-trees',
    name: 'Forest Guardian',
    description: 'Save 100 trees',
    category: 'eco',
    icon: '🌲',
    threshold: 100,
    metric: 'treesSaved',
  },
  // Special
  {
    id: 'level-5',
    name: 'Rising Star',
    description: 'Reach level 5',
    category: 'special',
    icon: '⭐',
    threshold: 5,
    metric: 'level',
  },
  {
    id: 'level-10',
    name: 'Focus Master',
    description: 'Reach level 10',
    category: 'special',
    icon: '🌟',
    threshold: 10,
    metric: 'level',
  },
];

export const ACHIEVEMENT_CATEGORY_LABELS: Record<Achievement['category'], string> = {
  productivity: 'Productivity',
  streak: 'Streak',
  eco: 'Eco',
  special: 'Special',
};
